apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: "2020-08-23T19:07:24Z"
    generation: 1
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:podManagementPolicy: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector:
            f:matchLabels:
              .: {}
              f:app: {}
          f:serviceName: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"myapp"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"AKKA_ACTOR_SYSTEM_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"AKKA_REMOTING_BIND_HOST"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"AKKA_REMOTING_BIND_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"AKKA_SEED_NODES"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"CLUSTER_MEMBERSHIP_ASK_TIMEOUT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"HTTP_HOST"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"HTTP_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":2551,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:tcpSocket:
                      .: {}
                      f:port: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
          f:updateStrategy:
            f:rollingUpdate:
              .: {}
              f:partition: {}
            f:type: {}
      manager: oc
      operation: Update
      time: "2020-08-23T19:07:24Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:collisionCount: {}
          f:currentReplicas: {}
          f:currentRevision: {}
          f:observedGeneration: {}
          f:replicas: {}
          f:updateRevision: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-08-23T19:07:26Z"
    name: myapp
    namespace: akka
    resourceVersion: "8894309"
    selfLink: /apis/apps/v1/namespaces/akka/statefulsets/myapp
    uid: 07520beb-f272-48cc-ae96-0a5c69ec60b3
  spec:
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: myapp
    serviceName: myapp
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: myapp
      spec:
        imagePullSecrets:
          - name: marcsecretquay
        containers:
        - env:
          - name: AKKA_ACTOR_SYSTEM_NAME
            value: myapp
          - name: AKKA_REMOTING_BIND_PORT
            value: "2551"
          - name: AKKA_REMOTING_BIND_HOST
            value: $HOSTNAME.myapp.default.svc.cluster.local
          - name: AKKA_SEED_NODES
            value: myapp-0.myapp.default.svc.cluster.local:2551,myapp-1.myapp.default.svc.cluster.local:2551,myapp-2.myapp.default.svc.cluster.local:2551
          - name: HTTP_HOST
            value: 0.0.0.0
          - name: HTTP_PORT
            value: "9000"
          - name: CLUSTER_MEMBERSHIP_ASK_TIMEOUT
            value: "5000"
          image: quay.io/marcf5/php-ubi
          imagePullPolicy: IfNotPresent
          name: myapp
          ports:
          - containerPort: 2551
            name: akka-remote
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 2551
            timeoutSeconds: 30
          resources:
            limits:
              cpu: 250m
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 384Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    collisionCount: 0
    currentReplicas: 1
    currentRevision: myapp-7685c9c9c5
    observedGeneration: 1
    replicas: 1
    updateRevision: myapp-7685c9c9c5
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
